force-app/main/default/objects/Currency__c/Currency__c.object-meta.xml
<CustomObject>
    <label>Currency</label>
    <nameField>
        <label>Currency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Currency__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Denotes whether this currency is currently used or historical</description>
    <inlineHelpText>Denotes whether this currency is currently used or historical</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Currency__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>Unique 3-letter code identifying this currency</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique 3-letter code identifying this currency</inlineHelpText>
    <label>Code</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Currency__c/fields/Decimal_Digits__c.field-meta.xml
<CustomField>
    <fullName>Decimal_Digits__c</fullName>
    <description>Number of decimal digits this currency supports</description>
    <inlineHelpText>Number of decimal digits this currency supports</inlineHelpText>
    <label>Decimal Digits</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Currency__c/fields/Name_Plural__c.field-meta.xml
<CustomField>
    <fullName>Name_Plural__c</fullName>
    <description>Plural name for this currency</description>
    <inlineHelpText>Plural name for this currency</inlineHelpText>
    <label>Name Plural</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Currency__c/fields/Rounding__c.field-meta.xml
<CustomField>
    <fullName>Rounding__c</fullName>
    <label>Rounding</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Currency__c/fields/Symbol__c.field-meta.xml
<CustomField>
    <fullName>Symbol__c</fullName>
    <description>Symbol of the currency in the Latin Alphabet</description>
    <inlineHelpText>Symbol of the currency in the Latin Alphabet</inlineHelpText>
    <label>Symbol</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Currency__c/fields/Symbol_Native__c.field-meta.xml
<CustomField>
    <fullName>Symbol_Native__c</fullName>
    <description>Local/native symbol of the currency</description>
    <inlineHelpText>Local/native symbol of the currency</inlineHelpText>
    <label>Symbol Native</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CurrencyService.cls
public with sharing class CurrencyService implements Queueable, Database.AllowsCallouts {
    
    public CurrencyService() {}

    public void execute(QueueableContext context) {
        sync();

        // Schedule next job if Retention_Days__c is configured for the "settings" custom MD record
        RatesService service = new RatesService();
        if(service.isRetentionDaysConfigured()) {
            System.enqueueJob(new RatesService());
        }
    }

    public void sync() {
        // Check Usage Limits
        FreeCurrencyApiResponses.StatusResponse status = FreeCurrencyApiClient.getStatus();
        System.debug('Remaining calls: ' + FreeCurrencyApiClient.getRemainingApiCalls());
        if(FreeCurrencyApiClient.getRemainingApiCalls() < 1) {
            return;
        }

        // Perform Callout
        FreeCurrencyApiResponses.CurrenciesResponse currencies = FreeCurrencyApiClient.getCurrencies();
        System.debug('Currencies Response:\n' + currencies);

        // Stage records for upsert
        List<Currency__c> currenciesToUpsert = new List<Currency__c>();
        for(FreeCurrencyApiResponses.CurrencyInfo curr : currencies.data.values()) {
            // Safely coerce data types
            Decimal decimalDigits = curr.decimal_digits == null ? null : Decimal.valueOf(curr.decimal_digits);
            Decimal rounding = curr.rounding == null ? null : Decimal.valueOf(curr.rounding);

            currenciesToUpsert.add(
                new Currency__c(
                    Name = curr.name,
                    Symbol__c = curr.symbol,
                    Symbol_Native__c = curr.symbol_native,
                    Decimal_Digits__c = decimalDigits,
                    Rounding__c = rounding,
                    Code__c = curr.code,
                    Name_Plural__c = curr.name_plural,
                    Active__c = true
                )
            );
        }

        if(currenciesToUpsert.isEmpty()) {
            return;
        }

        // Upsert Existing Currencies
        System.debug(currenciesToUpsert.size() + ' currencies to upsert\n' + currenciesToUpsert);
        Database.upsert(currenciesToUpsert, Currency__c.Fields.Code__c, false);

        // Deactivate historical currencies
        Set<Id> existingCurrencyIds = new Set<Id>();
        for(Currency__c curr : currenciesToUpsert) {
            existingCurrencyIds.add(curr.Id);
        }

        List<Currency__c> currenciesToDeactivate = new List<Currency__c>();
        for(Currency__c curr : [SELECT Active__c FROM Currency__c WHERE Id NOT IN :existingCurrencyIds AND Active__c = TRUE]) {
            curr.Active__c = false;
            currenciesToDeactivate.add(curr);
        }

        if(!currenciesToDeactivate.isEmpty()) {
            update currenciesToDeactivate;
        }
    }
}